[glossary]
== Forkortelser

[glossary]
API:: application programming interface
CEN:: European Committee for Standardization
CSW:: Catalogue Service for the Web
DCAT:: Data Catalog Vocabulary
DG ENV:: Directorate-General for Environment
DIGIT:: Directorate-General for Digital Services
DS:: Dansk Standard
EDTF:: Extended Date Time Format
EPSG:: European Petroleum Survey Group
GML:: Geography Markup Language
IANA:: Internet Assigned Numbers Authority
IEC:: International Electrotechnical Commission
IETF:: Internet Engineering Task Force
INSPIRE:: Infrastructure for Spatial Information in Europe
ISO:: International Organization for Standardization
ITRS:: International Terrestrial Reference System
ITU:: International Telecommunication Union
IXDTF:: Internet Extended Date/Time Format
JRC:: Joint Research Centre
MIG:: INSPIRE Maintenance and Implementation Group
OGC:: Open Geospatial Consortium
OMG:: Object Management Group
PDF:: Portable Document Format
RDF:: Resource Description Framework
SEMIC:: Semantic Interoperability Community
SFA:: simple feature access
SLD:: Styled Layer Descriptor
SQL:: Structured Query Language
TC:: Technical Committee
UML:: Unified Modeling Language
UTC:: Coordinated Universal Time
W3C:: World Wide Web Consortium
WFS:: Web Feature Service
WKB:: Well-Known Binary
WKT:: Well-Known Text
WMS:: Web Map Service
WMTS:: Web Map Tile Service
XMI:: XML Metadata Interchange
XML:: Extensible Markup Language
XSLT:: Extensible Stylesheet Language Transformations