[#identifikatorer]
=== Identifikatorer

Et objekt skal have en identifikator som er entydig, og som ikke ændres over tid. Identifikatoren skal som minimum være unik inden for datasættet objektet
indgår i, og må gerne være globalt unik. Tildeling og publicering af
identifikatorer er grundlæggende for at støtte oprettelsen af referencer fra andre data til ens egne data,
og dermed for at sammensætte data på tværs af datasæt. Data udstillet gennem det 
https://datafordeler.dk/[fællesoffentlige grunddataprogram] 
indeholder identifikatorer. Når et nyt register eller et nyt datasæt skal
etableres, kan man finde gode råd i nedenstående dokumenter.

Ofte vil et objekt, ud over den unikke identifikator, have en eller flere forretningsnøgler. For eksempel har en
matrikel et matrikelnummer og et naturbeskyttelsesområde omfattet af [.cite]#https://www.retsinformation.dk/eli/lta/2023/1098[Habitatbekendtgørelsen]# en
Natura 2000-kode. Det er som regel forretningsnøglerne, som vil være omtalt i lovgivningen,
hvorimod de unikke identifikatorer bruges til system-til-system-kommunikation.

[#linked-identifiers-schemes]
==== Linked identifier schemes

[.bibliographicaldetails]
GEOSPATIAL COMMISSION, _Linked identifier schemes: Best practice guide. oktober 2019._
Tilgængelig på: https://www.gov.uk/government/publications/linked-identifier-schemes-best-practice-guide[https://www.gov.uk/government/publications/linked-identifier-schemes-best-practice-guide,title=Linked identifier schemes: Best practice guide]

[.cite]#https://www.gov.uk/government/publications/linked-identifier-schemes-best-practice-guide[Linked identifier schemes: Best practice guide]# indeholder praktiske anbefalinger til hvordan identifikatorer skal udformes,
oprettes og administreres for at gøre det let for brugerne at forstå og kombinere data fra forskellige
kilder.

[NOTE]
Der eksisterer p.t. ikke et tilsvarende dansk dokument.

[#rfc9562]
==== RFC 9562, Universally Unique IDentifiers (UUIDs)

[.bibliographicaldetails]
IETF. RFC 9562, _Universally Unique IDentifiers (UUIDs)_. maj 2024. Tilgængelig på: https://www.rfc-editor.org/info/rfc9562[https://www.rfc-editor.org/info/rfc9562,title=Universally Unique IDentifiers (UUIDs)]

[.cite]#https://www.rfc-editor.org/info/rfc9562[RFC 9562]# specificerer genereringen af “universally unique identifiers” (UUID’er). En UUID er en 128-bit identifikator som er unik på tværs af både tid og rum. Generering af UUID'er kræver ikke en registreringsmyndighed for hver enkelt identifikator. RFC 9562 definerer også en Uniform Resource Name (URN) namespace for UUID'er.

Selve begrebet "UUID" er defineret i [.cite]#DCE 1.1: Remote Procedure Call#, Appendix A <<dce-11-rpc>>.

[NOTE]
[.cite]#RFC 9562# er relateret til [.cite]#ITU.X.667# <<itu-t-x-667>>, se RFC 9562, afsnit 1. Standarderne er mest relevant for software der skal generere UUID’er. De er dog også relevant i
konteksten af dette dokument, da det er vigtigt, at have en konsistent præsentation af
identifikatorer, se <<linked-identifiers-schemes>>. [.cite]#ITU-T X.667# <<itu-t-x-667>> specificerer anbefalinger til menneskevenlige
præsentationer.