[#metadata]
=== Metadata

For at kunne understøtte anvendelsen af stedbestemt information i
forhold til lovgivning er det nødvendigt med oplysninger om, hvordan man
har indsamlet data, hvad et datasæt kan i udgangspunkt kan anvendes til,
hvem der har ansvaret for datasættet, og hvad kvaliteten af det er. Det
hedder under ét metadata og er en slags varedeklaration. Metadata kan
bruges til at kunne fremfinde såvel gældende som historisk stedbestemt
information.

Metadata består her af såvel en varedeklaration af data som en
beskrivelse af kvaliteten af data.

[.cite]#INSPIRE-loven# fastsætter krav om, at der oprettes en national
metadataportal med de data som er omfattet af loven. Forskellige
datadomæner (fx domæner omhandlende geodata, statistiske data, åbne
data, arkivdata, …) har forskellige direktiver, forordninger, standarder
og best practices. Det har resulteret i forskellige, sameksisterende
dataportaler, både i Danmark og i Europa. Som dataleverandør bør det
være sådan, at man kun behøver at publicere sine metadata én enkelt
gang, derfra kan metadata evt. høstes fra andre portaler. På kort sigt
kan problemstillingen løses ved at oversætte en standard til en anden,
med uundgåelig tab af nogle metadataelementer. På lang sigt er
løsningen, at de internationale standardiseringsorganer harmoniserer
metadatastandarderne.

[#19115]
==== DS/EN ISO 19115 Metadata

[.bibliographicaldetails]
DS/EN ISO 19115:2005, _Geografisk information – Metadata_ 

[.cite]#DS/EN ISO 19115# beskriver geografiske metadata på en struktureret måde.
Standarden definerer de elementer som en beskrivelse består af, den
indeholder en model, der beskriver elementernes indbyrdes relationer, og
endelig indeholder standarden en beskrivelse af, hvordan man kan udvide
med flere elementer, hvis der ikke allerede findes de rigtige i
standarden.

[.cite]#DS/EN ISO 19115:2005# ligger til grund for de metadata der skal leveres i
henhold til [.cite]#INSPIRE-loven#.

https://geodata-info.dk[Geodata-info.dk]
udstiller metadata i henhold til [.cite]#DS/EN ISO 19115:2005# og understøtter dermed
også [.cite]#INSPIRE-loven#. Det samme gør sig gældende for INSPIREs egen
https://inspire-geoportal.ec.europa.eu/[metadataportal].

Der findes XML-skemaer til denne standard, se [.cite]#<<19139,DS/ISO/TS 19139>>#.

[.cite]#DS/EN ISO 19115:2005# er formelt trukket tilbage af Dansk Standard og de to internationale
standardiseringsorganer CEN og ISO. Standarden er erstattet af 
[.cite]#<<19115-1,DS/EN ISO 19115-1:2014>>#.

[#19115-1]
==== DS/EN ISO 19115-1 Metadata - Part 1: Grundprincipper

[.bibliographicaldetails] 
DS/EN ISO 19115-1:2014, _Geografisk information - Metadata - Del 1: Grundprincipper_

[.cite]#DS/EN ISO 19115-1# beskriver geografiske metadata på en struktureret
måde. Standarden definerer de elementer som en beskrivelse består af,
den indeholder en model, der beskriver elementernes indbyrdes
relationer, og endelig indeholder standarden en beskrivelse af, hvordan
man kan udvide med flere elementer, hvis der ikke allerede findes de
rigtige i standarden.

https://geodata-info.dk[Geodata-info.dk]
udstiller metadata i henhold til [.cite]#DS/EN ISO 19115-1:2014#

[NOTE]
====
I forhold til [.cite]#<<19115,DS/EN ISO 19115:2005>># er de største ændringer sket i
forhold til datakvalitet, som er trukket helt ud. Nu peger alt hvad der
har med datakvalitet at gøre på [.cite]#<<19157-1,DS/EN ISO 19157-1:2023>># 
og [.cite]#DS/ISO/TS 19158:2013, Geografisk information - Kvalitetssikring af datatilførsel#. 
Endelig indeholder denne version af standarden resultatet af
ca. 10 år erfaring indsamlet fra en lang række af implementeringer.

Der findes https://schemas.isotc211.org/schemas/19115/[XML-skemaer til denne standard]. 
====

[#19115-2]
==== DS/EN ISO 19115-2 Metadata - Del 2: Udvidelse til indsamling og behandling 

[.bibliographicaldetails]
DS/EN ISO 19115-2:2019, _Geografisk information - Metadata - Del 2:
Udvidelse til indsamling og behandling_ 

[.cite]#DS/EN ISO 19115-2# udvider [.cite]#<<19115-1,DS/EN ISO 19115-1>># med de XML-skemaer, der kræves til
forbedret beskrivelse af indsamling og behandling af geografisk
information, herunder billeder. Inkluderet er målesystemernes egenskaber
og deres numeriske metoder og beregningsmetoder, der bruges til at
udlede geografisk information fra data. Dette dokument inkluderer
ligeledes en XML-indkodning til indsamling og behandling af metadata.

[NOTE] 
====
Der findes https://schemas.isotc211.org/schemas/19115/[XML-skemaer til denne standard]. 
====

[#19115-3]
==== DS/EN ISO 19115-3 Metadata - Del 3: XML-skemaimplementering af grundlæggende begreber 

[.bibliographicaldetails]
DS/EN ISO 19115-3:2023, _Geografisk information – Metadata – Del 3: XML-skemaimplementering af grundlæggende begreber_

[.cite]#DS/EN ISO 19115-3#  definerer og dokumenterer de XML-skemaer, der anvendes i 
[.cite]#DS/EN ISO 19115-1# og [.cite]#DS/EN ISO 19115-2#, herunder også regler der anvendes til at validerer bindinger/restriktioner fra standarderne der ikke bliver valideret af XML-skemaerne.


[#19119]
==== DS/EN ISO 19119 Tjenesteydelser

[.bibliographicaldetails]
DS/EN ISO 19119:2016, _Geografisk information – Tjenesteydelser_ 

[.cite]#DS/EN ISO 19119# definerer krav til, hvordan
en platformneutral og platformspecifik specifikation af webtjenester skal
oprettes, for at muliggøre, at en tjeneste kan specificeres uafhængigt
af en eller flere underliggende distribuerede computerplatforme.

[.cite]#DS/EN ISO 19119# definerer ligeledes, hvordan geografiske
tjenester skal kategoriseres i henhold til en servicetaksonomi baseret på
IT-arkitekturen og tillader også, at tjenester kan kategoriseres i
henhold til et brugslivscyklusperspektiv, samt i henhold til
domænespecifikke og brugerdefinerede servicetaksonomier, for at lette
supporten ved offentliggørelse og opdagelse af tjenester. 

[NOTE] 
====
Der findes https://schemas.isotc211.org/schemas/19119/[XML-skemaer til denne standard].
====

[#19139]
==== DS/ISO/TS 19139 Metadata - Implementering af XML-skema

[.bibliographicaldetails]
DS/ISO/TS 19139:2009, _Geografisk information - Metadata - Implementering af XML-skema_ 

[.cite]#DS/ISO/TS 19139# definerer Geographic MetaData XML (gmd) indkodning, en XML
Schema implementering af [.cite]#<<19115,DS/EN ISO 19115:2005>>#.

[NOTE] 
====
Der findes https://schemas.isotc211.org/schemas/19139/[XML-skemaer til denne standard].
====

[#19157]
==== DS/EN ISO 19157 Datakvalitet

[.bibliographicaldetails#19157-1]
DS/EN ISO 19157-1:2023, _Geografisk information - Datakvalitet – Del 1: Generelle krav_

[.bibliographicaldetails#19157-2]
DS/EN ISO 19157-2:2016, _Geografisk information - Datakvalitet - Del 2: Implementering af XML-skema_

[.cite]#ISO 19157-1# fastlægger principperne for beskrivelse af kvaliteten af
geografiske data.

* Den definerer elementer til beskrivelse af datakvaliteten
* Den definerer processen til definition af yderligere domænespecifikke elementer til beskrivelse af datakvalitet
* Den specificerer komponenter og strukturen af et register for kvalitetsmål
* Den specificerer elementer og opbygning af datakvalitetsmålinger
* Den beskriver generelle procedurer for vurdering af kvaliteten af
geografiske data
* Den beskriver principper for afrapportering af datakvalitet.

[.cite]#ISO 19157-1# definerer også et sæt data kvalitetsmål til brug ved
evaluering og rapportering af datakvalitet. Den gælder for
dataproducenter, der leverer kvalitetsoplysninger til at beskrive og
vurdere, hvor godt et datasæt er i overensstemmelse med
produktspecifikationen og til databrugere, der forsøger at bestemme, om
specifikke geografiske data er af tilstrækkelig kvalitet til deres
specifikke anvendelse. 

[NOTE] 
====
[.cite]#ISO 19157-1# fastlægger ikke nogle minimumskrav til datakvalitet for
geografiske data.

Der findes https://schemas.isotc211.org/schemas/19157/[XML-skemaer til denne standard].
====


[.cite]#ISO 19157-2# definerer datakvalitetskodning i XML. Det er en XML-skemaimplementering, der er afledt af [.cite]#ISO 19157-1# og datakvalitetsrelaterede begreber fra [.cite]#ISO 19115-2#.

[#tg-metadata]
==== Technical Guidance for the implementation of INSPIRE dataset and service metadata

[.bibliographicaldetails]
MIG. _Technical Guidance for the implementation of INSPIRE dataset and
service metadata based on ISO/TS 19139:2007_. Version 2.2.1. 1 januar
2025. Tilgængelig på: https://inspire-mif.github.io/technical-guidelines/metadata/metadata-iso19139/metadata-iso19139.html[https://inspire-mif.github.io/technical-guidelines/metadata/metadata-iso19139/metadata-iso19139.html,title=Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007] 

[.cite]#https://inspire-mif.github.io/technical-guidelines/metadata/metadata-iso19139/metadata-iso19139.html[Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007]# indeholder retningslinjer baseret på [.cite]#<<19115,DS/EN ISO 19115>># og [.cite]#<<19119,DS/EN ISO 19119>># 
for at leve op til
[.cite]#https://eur-lex.europa.eu/eli/reg/2008/1205/2008-12-24[INSPIRE-gennemførelsesbestemmelsen om metadata]#. 

[#dcat]
==== Data Catalog Vocabulary (DCAT)

[.bibliographicaldetails]
W3C. _Data Catalog
Vocabulary (DCAT) - Version 3_. W3C Recommendation. 22 august 2024. Tilgængelig på:
https://www.w3.org/TR/vocab-dcat-3/[https://www.w3.org/TR/vocab-dcat-3/,title=Data Catalog Vocabulary (DCAT) - Version 3] 

[.cite]#https://www.w3.org/TR/vocab-dcat-3/[DCAT]# gør det muligt for en udgiver at beskrive datasæt og datatjenester
i et katalog ved hjælp af en standardmodel og et vokabularium, der letter
for brug og sammenlægning af metadata fra flere kataloger. Dette kan øge
synligheden af datasæt og datatjenester. Det gør det også muligt at have
en decentral tilgang til offentliggørelse af data kataloger og gør
samlende søgning efter datasæt på tværs af kataloger i flere brancher
bruger den samme forespørgsel mekanisme og struktur. Aggregerede DCAT
metadata kan tjene som en manifestfil som en del af en digital bevaringsproces.

[.cite]#DCAT# er et RDF-vokabularium (**R**esource **D**escription **F**ramework)
designet til at lette interoperabilitet mellem datakataloger
offentliggjort på Internettet. [.cite]#DCAT# definerer et skema og giver
eksempler til anvendelser. 

[NOTE] 
====
[.cite]#DCAT-AP-DK#, en delmængde af [.cite]#DCAT-AP#, som igen er en delmængde af [.cite]#DCAT#,
benyttes til det https://datavejviser.dk/[fælles offentlige datasætkatalog], der giver overblik
over hvilke offentlige datasæt, der findes, hvor de findes, om de er
tilgængelige og hvem der udgiver de offentlige datasæt.

Datasætkataloget indeholder alene metadata, dvs. en beskrivelse af
datasættet, og indeholder ikke rådata.
====

[#geodcat-ap]
==== GeoDCAT-AP

[.bibliographicaldetails]
JRC, DG ENV og DIGIT. _GeoDCAT-AP_. Version 3.0.0. 4. oktober 2024. Tilgængelig på: https://semiceu.github.io/GeoDCAT-AP/releases/3.0.0/[https://semiceu.github.io/GeoDCAT-AP/releases/3.0.0/,title=GeoDCAT-AP]. 

[.cite]#https://semiceu.github.io/GeoDCAT-AP/releases/3.0.0/[GeoDCAT-AP 3.0.0]# er en udvidelse af [.cite]#<<dcat,DCAT>>#, som bruges i åbne dataportaler og e-government-domænet, med 
oplysninger om geografiske datasæt som specificeret i ISO/TC 211-standarderne
standarderne og INSPIRE-specifikationen for metadata, som bruges indenfor det geografiske
domæne. [.cite]#GeoDCAT-AP# har - fordi det er baseret på RDF (**R**esource
**D**escription **F**ramework) - muligheden for at offentliggøre
metadata direkte på nettet uden åbne og geografiske dataportaler.