[#tid-historik]
=== Tid og historik

Virksomheder og myndigheder håndterer forskellige ting som er vigtige i deres dagligdag. Det kan være fysiske objekter (f.eks. bygninger) eller mere abstrakte begreber (f.eks. aftaler eller kunder). Disse ting betegnes _forretningsobjekter_.

NOTE: Der skelnes mellem typer af forretningsobjekter og instanser af forretningsobjekter. F.eks. dit hus, mit hus og vores kontor er alle tre instanser af typen “bygning”. Man kan også sige at dit hus, mit hus og vores kontor er eksemplarer, forekomster eller individer af klassen, slagsen eller almenbegrebet “bygning”. “Forretningsobjekt” anvendes her som synonym for "forretningsobjektinstans".

For at en virksomhed eller myndighed kan holde styr på data om sine forretningsobjektinstanser, registreres deres repræsentationer, kaldt _dataobjekter_, i et _informationssystem_. Forretningsobjekter befinder sig i virkeligheden, hvorimod dataobjekter befinder sig i informationssystemer, og er information om virkeligheden.

Virkeligheden er i stadig forandring; et forretningsobjekt kan ændre sig og dermed befinde sig i en ny tilstand. Man kan derfor stille følgende tre spørgsmål om et forretningsobjekt:

. Hvordan er forretningsobjektet lige nu?
. Hvordan var forretningsobjektet på et givet tidspunkt i fortiden?
. Hvordan vil forretningsobjektet være på et givet tidspunkt i fremtiden?

[NOTE]
====
Når man f.eks. er interesseret i et hus’ udseende (farve, form, osv.), kan spørgsmålene formuleres som følgende:

. Hvordan ser huset ud lige nu?
. Hvordan så huset ud på et givet tidspunkt i fortiden?
. Hvordan vil huset se ud på et givet tidspunkt i fremtiden?
====

Hvis der i et informationssystem registreres hvornår et forretningsobjekt har ændret sig eller vil ændre sig, så understøtter informationssystemet _virkningstid_ og kan det svare på ovenstående tre spørgsmål.

Vores viden om virkeligheden er også i stadig forandring. Man kan derfor stille følgende to spørgsmål:

. Hvad ved man nu om forretningsobjektet? Eller rettere sagt, hvad tror man nu om forretningsobjektet?
. Hvad troede man på et givet tidspunkt i fortiden om forretningsobjektet?

Hvis der i et informationssystem registreres hvornår man har fået ny viden om et forretningsobjekt, så understøtter informationssystemet _registreringstid_ og kan det svare på ovenstående to spørgsmål.

Hvis der i et informationssystem registreres hvornår et forretningsobjekt har ændret sig eller vil ændre sig samt hvornår man har fået ny viden, så understøtter informationssystemet _bitemporalitet_ eller _dobbelthistorik_ og kan det svare på følgende seks spørgsmål:

. Hvad tror man nu om hvordan forretningsobjektet er lige nu?
. Hvad tror man nu om hvordan forretningsobjektet var på et givet tidspunkt i fortiden?
. Hvad tror man nu om hvordan forretningsobjektet vil være på et givet tidspunkt i fremtiden?
. Hvad troede man på et givet tidspunkt i fortiden om hvordan forretningsobjektet var på det tidspunkt?
. Hvad troede man på et givet tidspunkt i fortiden om hvordan forretningsobjektet var på et tidligere tidspunkt?
. Hvad troede man på et givet tidspunkt i fortiden om hvordan forretningsobjektet ville være på et senere tidspunkt?

Håndtering af tid i relationelle databaser beskrives udførligt i <<snodgrass>>. Designmønstre for håndtering af tid i software beskrives i <<fowl05>>. <<fowl05>> henviser også til forskelligt anden relevant litteratur.

[#temporal-databases]
==== The Consensus Glossary of Temporal Database Concepts

[.bibliographicaldetails]
JENSEN, Christian S. og DYRESON, Curtis E. The Consensus Glossary of 
Temporal Database Concepts—February 1998 Version. I: _Temporal 
Databases: Research and Practice_. Springer Berlin Heidelberg, 1998. p. 
367–405. Lecture Notes in Computer Science. 
doi:link:https://doi.org/10.1007/BFb0053710[10.1007/BFb0053710,title=The Consensus Glossary of Temporal Database Concepts—February 1998 Version (DOI)]. 
Tilgængelig på: https://infolab.usc.edu/csci599/Fall2001/paper/glossary.pdf[https://infolab.usc.edu/csci599/Fall2001/paper/glossary.pdf,title=The Consensus Glossary of Temporal Database Concepts—February 1998 Version]

Artiklen [.cite]#https://infolab.usc.edu/csci599/Fall2001/paper/glossary.pdf[The Consensus Glossary of Temporal Database Concepts]# indeholder termer og definitioner for begreber som
anvendes i temporale databaser, såsom “temporal”, “lifespan”, “valid
time”, osv. En forklaring for hvorfor en bestemt term, og ikke en anden
term, er valgt, er også til stede. Som titlen indikerer, er der tale om
resultatet af en proces for at opnå en højere grad af enhed ang.
navngivning og definitioner af begreber inden for dette domæne.

[NOTE]
“Virkningstid” og “registreringstid” 
svarer til artiklens begreber “Valid time”, henholdsvis “transaction 
time”.

[#9075-2]
==== ISO/IEC 9075-2, Database languages — SQL — Part 2: Foundation (SQL/Foundation) 

[.bibliographicaldetails]
ISO/IEC 9075-2, _Information technology — Database languages — SQL —
Part 2: Foundation (SQL/Foundation)_

[.cite]#ISO/IEC 9075#, standarden for Structured Query Language (SQL), er delt op i flere
dele. Del 2 definerer datastrukturer og grundlæggende operationer på
SQL-data.

[NOTE]
I [.cite]#ISO/IEC 9075-2# anvendes termen “application time” som synonym for
“valid time”, og “system time” som synonym for “transaction time”.
