[#tid-historik]
=== Tid og historik

Virksomheder og myndigheder håndterer forskellige ting som er vigtige i deres dagligdag. Det kan være fysiske objekter (f.eks. bygninger) eller mere abstrakte begreber (f.eks. aftaler eller kunder). Disse ting betegnes _forretningsobjekter_.

NOTE: Der skelnes mellem typer af forretningsobjekter og instanser af forretningsobjekter. F.eks. dit hus, mit hus og vores kontor er alle tre instanser af typen “bygning”. Man kan også sige at dit hus, mit hus og vores kontor er eksemplarer, forekomster eller individer af klassen, slagsen eller almenbegrebet “bygning”. “Forretningsobjekt” anvendes her som synonym for "forretningsobjektinstans".

For at en virksomhed eller myndighed kan holde styr på data om sine forretningsobjektinstanser, registreres deres repræsentationer, kaldt _dataobjekter_, i et _informationssystem_. Forretningsobjekter befinder sig i virkeligheden, hvorimod dataobjekter befinder sig i informationssystemer, og er information om virkeligheden.

Virkeligheden er i stadig forandring; et forretningsobjekt kan ændre sig og dermed befinde sig i en ny tilstand. Man kan derfor stille følgende tre spørgsmål om et forretningsobjekt:

. Hvordan er forretningsobjektet lige nu?
. Hvordan var forretningsobjektet på et givet tidspunkt i fortiden?
. Hvordan vil forretningsobjektet være på et givet tidspunkt i fremtiden?

[NOTE]
====
Når man f.eks. er interesseret i et hus’ udseende (farve, form, osv.), kan spørgsmålene formuleres som følgende:

. Hvordan ser huset ud lige nu?
. Hvordan så huset ud på et givet tidspunkt i fortiden?
. Hvordan vil huset se ud på et givet tidspunkt i fremtiden?
====

Hvis der i et informationssystem registreres hvornår et forretningsobjekt har ændret sig eller vil ændre sig, så understøtter informationssystemet _virkningstid_ og kan det svare på ovenstående tre spørgsmål.

Vores viden om virkeligheden er også i stadig forandring. Man kan derfor stille følgende to spørgsmål:

. Hvad ved man nu om forretningsobjektet? Eller rettere sagt, hvad tror man nu om forretningsobjektet?
. Hvad troede man på et givet tidspunkt i fortiden om forretningsobjektet?

Hvis der i et informationssystem registreres hvornår man har fået ny viden om et forretningsobjekt, så understøtter informationssystemet _registreringstid_ og kan det svare på ovenstående to spørgsmål.

Hvis der i et informationssystem registreres hvornår et forretningsobjekt har ændret sig eller vil ændre sig samt hvornår man har fået ny viden, så understøtter informationssystemet _bitemporalitet_ eller _dobbelthistorik_ og kan det svare på følgende seks spørgsmål:

. Hvad tror man nu om hvordan forretningsobjektet er lige nu?
. Hvad tror man nu om hvordan forretningsobjektet var på et givet tidspunkt i fortiden?
. Hvad tror man nu om hvordan forretningsobjektet vil være på et givet tidspunkt i fremtiden?
. Hvad troede man på et givet tidspunkt i fortiden om hvordan forretningsobjektet var på det tidspunkt?
. Hvad troede man på et givet tidspunkt i fortiden om hvordan forretningsobjektet var på et tidligere tidspunkt?
. Hvad troede man på et givet tidspunkt i fortiden om hvordan forretningsobjektet ville være på et senere tidspunkt?

[#temporal-databases]
==== Temporal Databases: Research and Practice

[.bibliographicaldetails]

JENSEN, Christian S. og DYRESON, Curtis E. The Consensus Glossary of 
Temporal Database Concepts—February 1998 Version. I: _Temporal 
Databases: Research and Practice_. Springer Berlin Heidelberg, 1998. p. 
367–405. Lecture Notes in Computer Science. 
doi:link:https://doi.org/10.1007/BFb0053710[10.1007/BFb0053710,title=The Consensus Glossary of Temporal Database Concepts—February 1998 Version (DOI)]. 
Tilgængelig på: https://infolab.usc.edu/csci599/Fall2001/paper/glossary.pdf[https://infolab.usc.edu/csci599/Fall2001/paper/glossary.pdf,title=The Consensus Glossary of Temporal Database Concepts—February 1998 Version]

Denne artikel indeholder termer og definitioner for begreber som
anvendes i temporale databaser, såsom “temporal”, “lifespan”, “valid
time”, osv. En forklaring for hvorfor en bestemt term, og ikke en anden
term, er valgt, er også til stede. Som titlen indikerer, er der tale om
resultatet af en proces for at opnå en højere grad af enhed ang.
navngivning og definitioner af begreber inden for dette domæne.

[NOTE]
Grunddataprogrammets begreber “virkningstid” og “registreringstid” 
svarer til artiklens begreber “Valid time”, henholdsvis “transaction 
time”.

[#9075-2]
==== ISO/IEC 9075-2, Database languages — SQL — Part 2: Foundation (SQL/Foundation) 

[.bibliographicaldetails]
ISO/IEC 9075-2, _Information technology — Database languages — SQL —
Part 2: Foundation (SQL/Foundation)_

ISO-standarden for Structured Query Language (SQL) er delt op i flere
dele. Del 2 definerer datastrukturer og grundlæggende operationer på
SQL-data.

[NOTE]
I SQL-standarden anvendes termen “application time” som synonym for
“valid time”, og “system time” som synonym for “transaction time”.

[#bitemporalitet-poc]
==== Bitemporalitet, proof of concept

[.bibliographicaldetails]
GEODATASTYRELSEN og KL. _Bitemporalitet. Proof of concept_. 19 september 2014. [Set 11 februar 2020]. Tilgængelig på:
http://arkitekturguiden.digitaliser.dk/sites/default/files/ctools/bitemporalitet-v1.2.pdf[http://arkitekturguiden.digitaliser.dk/sites/default/files/ctools/bitemporalitet-v1.2.pdf,title=Bitemporalitet. Proof of concept]

Rapporten beskriver en række problemstillinger omkring historik og
bitemporalitet, som er relevante i forhold til at distribuere data med
høj aktualitet og med en datahistorik der giver sporbarhed i de
foretagne registreringer. Dokumentet anvender en konstrueret matrikulær
udstykning som showcase til at forklare egenskaber og konsekvenser ved
modellering af bitemporale egenskaber.

Dokumentet blev skrevet for at skabe mere tydelighed om
reglen om dobbelthistorikunderstøttelse fra Grunddata-modelreglerne 
<<gd-modelregler>>.

[#sdfe-regler-historik]
==== Regelsæt for historik i data 

[.bibliographicaldetails] 
SDFE, _Regelsæt for historik i data_ [igangværende arbejde]

Dokumentet beskrives tre sæt af historikmodeller, som understøtter
forskellig funktionalitet vedrørende forvaltede objekters livscyklus og
de udtræk, der gør historikken brugbar.

Dokumentet indeholder beskrivelse af et begrebsapparat, der kommunikerer
en relativt kompleks, men også en konsistent og implementérbar model, der
kan danne baggrund for håndtering af historik i data, der udstiller
offentligt forvaltede objekter.

Til sidst er der en beskrivelse af, hvordan historikken anvendes i
forbindelse med andre attributter, såsom status, med det formål at
styrke den forretningsmæssige brug af data.

[NOTE] 
SDFE har p.t. et eksisterende regelsæt, som skal revideres.

[#snodgrass]
==== Developing time-oriented database applications in SQL

[.bibliographicaldetails] 
SNODGRASS, Richard T. _Developing time-oriented database applications in
SQL_. San Francisco, California : Morgan Kaufmann Publishers, juli 1999.
ISBN 1-55860-436-7. Tilgængelig på:
link:++https://www2.cs.arizona.edu/~rts/tdbbook.pdf++[++https://www2.cs.arizona.edu/~rts/tdbbook.pdf++,title=Developing time-oriented database applications in SQL] 

Bogen er den mest omfattende behandling af håndtering af tid i
relationelle databaser der findes og var den vigtigste kilde for
ovenstående rapport.

[#fowler-temporal-patterns]
==== Further Patterns of Enterprise Application Architecture

[.bibliographicaldetails]
FOWLER, Martin. Temporal Patterns. _Further Patterns of Enterprise
Application Architecture_. 16 februar 2005. [Set 11 februar 2020].
Tilgængelig på:
https://martinfowler.com/eaaDev/timeNarrative.html[https://martinfowler.com/eaaDev/timeNarrative.html,title=Temporal Patterns]

Indlægget beskriver problematikken ang. tidsdimensioner og præsenterer
forskellige designmønstre (“design patterns”) for at håndtere
forskellige grader af tidsunderstøttelse i software. Derudover henviser
indlægget til forskelligt anden relevant litteratur. 
