[#indkodninger]
=== Udveksling af geodata - indkodninger 
Når data skal udveksles mellem digitale systemer, skal de ændres til en
form (format), der kan forstås af to eller flere systemer. Et sæt regler
for hvordan man konverterer data, så det følger et bestemt format,
kalder man en indkodning. Der eksisterer forskellige indkodninger for
geodata. Ofte følger der med en datastruktur også et skema med, dvs. en
formel beskrivelse af planen for datastrukturen.

Nedenunder beskrives de vigtigste åbne specifikationer for indkodning af
vektordata.

[NOTE]
====
JSON <<rfc-8259>> og GeoJSON <<rfc-7946>>, udviklet
i regi af Internet Engineering Task Force (IETF), er ikke med i <<indkodninger>>. Det skyldes, at måden, hvorpå koordinater i koordinatsystemer relevant for Danmark og Grønland kan indkodes i (Geo)JSON ikke er standardiseret endnu.
====

[#gml]
==== Geography Markup Language (GML)

[.bibliographicaldetails#gml-32]
OGC 07-036r1, _OpenGIS® Geography Markup Language (GML) Encoding
Standard_. Version 3.2.2. 5 december 2016. Tilgængelig på:
https://portal.opengeospatial.org/files/?artifact_id=74183&version=2[https://portal.opengeospatial.org/files/?artifact_id=74183&version=2,title=OpenGIS® Geography Markup Language (GML) Encoding Standard] 

[.cite]#https://portal.opengeospatial.org/files/?artifact_id=74183&version=2[OpenGIS® Geography Markup Language (GML) Encoding Standard]# 
specificerer en indkodning i Extensible Markup Language
(XML) for bl.a. hovedparten af begreberne defineret i
[.cite]#<<19103,DS/EN ISO 19103>># og [.cite]#<<19107,DS/EN ISO 19107>>#.

GML-data beskrives af et GML-applikationsskema, et XML-skema som
anvender elementer fra skemaerne defineret af GML-standarden.

Standarden indeholder et sæt regler, der definerer, hvordan man på
systematisk vis kan omsætte en logisk datamodel der er i
overensstemmelse med [.cite]#<<19103,DS/EN ISO 19103>># til et GML-applikationsskema.

Standarden er også kendt som [.cite]#DS/EN ISO 19136-1:2020, Geografisk information — GML (Geography Markup Language) — Del 1: Grundprincipper#.

[IMPORTANT]
====
Skemadokumenterne for GML 3.2 findes på
http://schemas.opengis.net/gml/3.2.1/[http://schemas.opengis.net/gml/3.2.1/,title=skemadokumenterne for GML 3.2]. Den sidste undermappe burde have heddet 3.2.2 i stedet for 3.2.1, det er en fejl fra OGC’s side. Den nuværende version, inklusiv patch-nummer, er 3.2.*2*. 
Skemadokumenterne kan ligeledes findes på https://schemas.opengis.net/gml/ som zip-filer til download. Der findes en zip-fil til version 3.2.2.
====

[NOTE]
====
Da der er tale om XML-data, kan man anvende alle sprog der hører til
XML-familien, såsom XML Schema <<xmlschema-0>>, Extensible Stylesheet Language Transformations
(XSLT) <<xslt-30>> og Schematron <<schematron>>, og alle værktøjer, der kan håndtere disse sprog. Det vil også sige, at GML bør bruges, når data skal valideres, da både
XML Schema og Schematron er konstrueret til det formål.

Standarden er moden, der forventes ikke nye versioner udover eventuelle
fejlrettelser.

Der findes applikationer, der har implementeret reglerne der kan omsætte en
logisk datamodel der er i overensstemmelse med [.cite]#<<19103,DS/EN ISO 19103>># 
til et GML-applikationsskema. Et eksempel er https://shapechange.github.io/ShapeChange/[ShapeChange].

GML kan anvendes til udveksling af hele datasæt (fildownload) eller til
udveksling af et udvalg af features fra et datasæt via en webtjeneste.

GML version 3.1.1 <<gml311>> er stadigvæk i brug, fx i [.cite]#<<#bek128>># og i visse implementationer af [.cite]#<<sql-mm,SQL/MM>>#. Skemadokumenter til denne version kan findes på https://schemas.opengis.net/gml/3.1.1/.
====

[.bibliographicaldetails#gml-33] 
OGC 10-129r1, _OGC® Geography Markup Language (GML) — Extended schemas
and encoding rules_. Version 3.3.0. 7 februar 2012. Tilgængelig på:
https://portal.opengeospatial.org/files/?artifact_id=46568[https://portal.opengeospatial.org/files/?artifact_id=46568,title=OGC® Geography Markup Language (GML) — Extended schemas and encoding rules]

[.cite]#https://portal.opengeospatial.org/files/?artifact_id=46568[OGC® Geography Markup Language (GML) — Extended schemas and encoding rules]#, GML 3.3-standarden, er en udvidelse af <<gml-32,GML 3.2-standarden>>. Standarden indeholder bl.a. en indkodning for elementerne defineret i
DS/EN ISO 19148, _Geografisk information — Lineær reference-system_ og
kompakte indkodninger af almen anvendte GML-geometrier såsom flader.

Standarden er også kendt som [.cite]#DS/EN ISO 19136-2:2018, Geografisk information — GML (Geography Markup Language) — Del 2: Udvidede skemaer 
og kodningsregler#.

[IMPORTANT]
====
GML 3.3-standarden, er en _udvidelse_ af GML 3.2-standarden, ikke en
_erstatning_ for GML 3.2-standarden. Det forhold afspejles bedre i ISO-numrene for de tilsvarende ISO-standarder, hvor man har ISO 19136-serien, som består af to dele:

* DS/EN ISO 19136-1:2020, _Geografisk information — GML (Geography Markup Language) — Del 1: Grundprincipper_
* DS/EN ISO 19136-2:2018, _Geografisk information — GML (Geography Markup Language) — Del 2: Udvidede skemaer og kodningsregler_
====

[NOTE] 
====
Skemadokumenterne for GML 3.3 findes på
http://schemas.opengis.net/gml/3.3/[http://schemas.opengis.net/gml/3.3/,title=skemadokumenterne for GML 3.3]. Skemadokumenterne kan ligeledes findes på https://schemas.opengis.net/gml/ som zip-filer til download, der findes en zip-fil til version 3.3.1.

Standarden er moden, der forventes ikke nye versioner udover eventuelle
fejlrettelser.
====

[#gml-sf]
==== Geography Markup Language (GML) simple features profile

[.bibliographicaldetails] 
OGC 10-100r3, _Geography Markup Language (GML) simple features profile
(with Corrigendum)_. Version 2.0. 5 april 2012. Tilgængelig på:
http://portal.opengeospatial.org/files/?artifact_id=42729[http://portal.opengeospatial.org/files/?artifact_id=42729,title=Geography Markup Language (GML) simple features profile (with Corrigendum)]

GML-standarden er en meget omfattende standard, og derfor har OGC
defineret en begrænset men nyttigt delmængde af den, for at få mere
software til at understøtte GML.
[.cite]#http://portal.opengeospatial.org/files/?artifact_id=42729[Geography Markup Language simple features profile (GML-SF)]# begrænser udvalget af geometrier i GML til 0-,
1-, og 2-dimensionelle geometrier beskrevet i 1-, 2-, eller
3-dimensionale koordinatsystemer og begrænser antallet af måder
man kan indkode disse geometrier på.

[.cite]#GML-SF# definerer tre compliance-niveauer, SF-0, SF-1 og SF-2. Niveau
SF-2 tillader en database der implementerer [.cite]#<<sfa-sql,SFA-SQL>># at
repræsentere de data, den måtte indeholde.

I modsætning til [.cite]#<<sfa-ca,SFA-CA>># tillader [.cite]#GML-SF# også bestemte indkodninger for
cirkelbuer og cirkler (`+gml:Arc+`, `+gml:Circle+` og `+gml:CircleByCenterPoint+`).

[#gpkg]
==== GeoPackage Encoding Standard 

[.bibliographicaldetails] 
OGC 12-128r19, _OGC® GeoPackage Encoding Standard - with Corrigendum_.
Version 1.4.0. 6 februar 2024. Tilgængelig på:
https://docs.ogc.org/is/12-128r19/12-128r19.html[https://docs.ogc.org/is/12-128r19/12-128r19.html,title=OGC® GeoPackage Encoding Standard] 

[.cite]#https://docs.ogc.org/is/12-128r19/12-128r19.html[OGC® GeoPackage Encoding Standard]# er baseret på https://sqlite.org/[SQLite], et relationelt
databasehåndteringssystem. Én GeoPackage-fil kan håndtere vektordata,
rasterdata, og metadata. Da en GeoPackage er en databasecontainer,
understøtter den direkte brug, fx til analyseformål.

[.cite]#OGC® GeoPackage Encoding Standard# er i overensstemmelse med [.cite]#<<sfa>>#.

[NOTE] 
====
I Nederlandene er GeoPackage-standarden optaget på
https://www.forumstandaardisatie.nl/open-standaarden/verplicht[følg-eller-forklar
listen] af “Dutch Standardisation Forum”. Anvendelsesområdet for
GeoPackage er ifølge motiveringen for optagelse af listen følgende:
“GeoPackage skal anvendes når det offentlige tilbyder geodata til
download til tredjepart”.

Dutch Standardisation Forum understreger også, at “GeoPackage ikke ses
som en erstatning, men som et supplement til brugen af GML”.

GeoPackage ses at være en erstatning for shapefiler.

GeoPackage anvendes typisk til udveksling af hele datasæt (fildownload). Formatet kan desuden anvendes til at lagre hele datasæt.

GeoPackage bør bruges når man vil distribuere data i andre formater, ved
siden af GML.
====

[#citygml]
==== CityGML

[.bibliographicaldetails] 
OGC 20-010, _OGC City Geography Markup Language (CityGML) Part 1: Conceptual Model Standard_. Version 3.0. 2 marts 2021. Tilgængelig på:
https://docs.ogc.org/is/20-010/20-010.html[https://docs.ogc.org/is/20-010/20-010.html,title=OGC City Geography Markup Language (CityGML) Part 1: Conceptual Model Standard] 

[.cite]#https://docs.ogc.org/is/20-010/20-010.html[OGC City Geography Markup Language (CityGML) Part 1: Conceptual Model Standard]# standard definerer en konceptuel model til repræsentation, lagring og udveksling af virtuelle 3D-bymodeller.

[.bibliographicaldetails] 
OGC 21-006r2, _OGC City Geography Markup Language (CityGML) Part 2: GML Encoding Standard_. Version 3.0. 20 juni 2023. 
Tilgængelig på https://docs.ogc.org/is/21-006r2/21-006r2.html[https://docs.ogc.org/is/21-006r2/21-006r2.html,titel=OGC 21-006r2 OGC City Geography Markup Language (CityGML) Part 2: GML Encoding Standard]

[.cite]#https://docs.ogc.org/is/21-006r2/21-006r2.html[OGC City Geography Markup Language (CityGML) Part 2: GML Encoding Standard]# dokumenterer OGC GML-implementeringsspecifikationen (IS) for CityGML 3.0-begrebsmodellen. CityGML 3.0-begrebsmodellen er en platformsuafhængig model (PIM). Den definerer begreber på en måde, der er uafhængig af enhver implementeringsteknologi. Som sådan kan CityGML-begrebsmodellen ikke implementeres direkte. Den fungerer snarere som grundlag for platformspecifikke modeller (PSM). En PSM tilføjer til PIM de teknologispecifikke detaljer, der er nødvendige for fuldt ud at definere CityGML-modellen til brug med en bestemt teknologi. PSM kan derefter bruges til at generere skemaet og andre artefakter, der er nødvendige for at opbygge CityGML 3.0-implementeringer.

Standarden definerer PSM'er og skemaer for CityGML 3.0-implementeringsspecifikationen (IS) for implementeringer af Geography Markup Language (GML). GML-skemaerne forklares i en oversigt, og de designbeslutninger, der er truffet, er også dokumenteret.

UML-modellen findes som https://github.com/opengeospatial/CityGML-3.0CM/releases/download/3.0.0-final.2021.02.23/CityGML_3.0_Consolidated_Draft.eap[Enterprise Architect-fil] og som https://github.com/opengeospatial/CityGML-3.0CM/releases/download/3.0.0-final.2021.02.23/XMI.Files.zip[XMI-filer].

XML-skemaer kan findes på http://schemas.opengis.net/citygml.

 
[#pdf-georegistration]
==== PDF Georegistration Encoding Best Practice 

[.bibliographicaldetails] 
OGC 08-139r3, _PDF Georegistration Encoding Best Practice_. OGC Best
Practice. Version 2.2. 17 januar 2011. Tilgængelig på:
https://portal.opengeospatial.org/files/?artifact_id=40537[https://portal.opengeospatial.org/files/?artifact_id=40537,title=PDF Georegistration Encoding Best Practice]

[.cite]#https://portal.opengeospatial.org/files/?artifact_id=40537[PDF Georegistration Encoding Best Practice]# beskriver hvordan man kan lave PDF-dokumenter
der er georefererede.

[NOTE] 
====
Se følgende dokumenter for mere information angående georefererede
PDF-dokumenter:

* [.cite]#A PDF Tile Model for Geographic Map Data# <<zamx19>>
* [.cite]#Creating Maps for the Non-Mapper# <<capu10>>
====
