[#indkodninger]
=== Udveksling af geodata - indkodninger 
Når data skal udveksles mellem digitale systemer, skal de ændres til en
form (format), der kan forstås af to eller flere systemer. Et sæt regler
for hvordan man konverterer data, så det følger et bestemt format,
kalder man en indkodning. Der eksisterer forskellige indkodninger for
geodata. Ofte følger der med en datastruktur også et skema med, dvs. en
formel beskrivelse af planen for datastrukturen.

Nedenunder beskrives de vigtigste åbne specifikationer for indkodning af
vektordata.

[#gml-32]
==== Geography Markup Language (GML) Encoding Standard 

[.bibliographicaldetails]
OGC 07-036r1, _OpenGIS® Geography Markup Language (GML) Encoding
Standard_. Version 3.2.2. 5 december 2016. Tilgængelig på:
https://portal.opengeospatial.org/files/?artifact_id=74183&version=2[https://portal.opengeospatial.org/files/?artifact_id=74183&version=2,title=OpenGIS® Geography Markup Language (GML) Encoding Standard] 

Denne standard specificerer en indkodning i Extensible Markup Language
(XML) for bl.a. hovedparten af begreberne defineret i
<<19103,DS/ISO 19103>>, <<19107,DS/EN ISO 19107>> og <<19111,DS/EN ISO 19111>>.

GML-data beskrives af et GML-applikationsskema, et XML-skema som
anvender elementer fra skemaerne defineret af GML-standarden.

Standarden indeholder et sæt regler, der definerer, hvordan man på
systematisk vis kan omsætte en logisk datamodel der er i
overensstemmelse med <<19103,DS/ISO 19103>> til et GML-applikationsskema.

Denne OGC-standard er også kendt som DS/EN ISO 19136-1:2020, _Geografisk 
information — GML (Geography Markup Language) — Del 1: Grundprincipper_. 

[NOTE]
====
Skemaerne for GML 3.2 ligger på
http://schemas.opengis.net/gml/3.2.1/[http://schemas.opengis.net/gml/3.2.1/,title=skemaerne for GML 3.2]
(det er en fejl fra OGC’s side, at den sidste undermappe hedder 3.2.1,
det burde have været 3.2).

Da der er tale om XML-data, kan man anvende alle sprog der hører til
XML-familien, såsom Extensible Stylesheet Language Transformations
(XSLT) og Schematron, og alle værktøjer, der kan håndtere disse sprog.

Det vil også sige, at GML bør bruges, når data skal valideres, da både
XML Schema og Schematron er konstrueret til det formål.

Standarden er moden, der forventes ikke nye versioner udover eventuelle
fejlrettelser.

Der findes software, der har implementeret reglerne der kan omsætte en
logisk datamodel der er i overensstemmelse med <<19103,DS/ISO 19103>> 
til et GML-applikationsskema.

GML kan anvendes til udveksling af hele datasæt (fildownload) eller til
udveksling af et udvalg af features fra et datasæt via en webtjeneste.
====

[#gml-33]
==== Geography Markup Language (GML) — Extended schemas and encoding rules 

[.bibliographicaldetails] 
OGC 10-129r1, _OGC® Geography Markup Language (GML) — Extended schemas
and encoding rules_. Version 3.3.0. 7 februar 2012. Tilgængelig på:
https://portal.opengeospatial.org/files/?artifact_id=46568[https://portal.opengeospatial.org/files/?artifact_id=46568,title=OGC® Geography Markup Language (GML) — Extended schemas and encoding rules] 

GML 3.3-standarden er en udvidelse af <<gml-32,GML 3.2-standarden>>, ikke en
erstatning for GML 3.2-standarden.

Standarden indeholder bl.a. en indkodning for elementerne defineret i
DS/EN ISO 19148, _Geografisk information — Lineær reference-system_ og
kompakte indkodninger af almen anvendte GML-geometrier såsom flader.

Denne OGC-standard er også kendt som DS/EN ISO 19136-2:2018, _Geografisk 
information — GML (Geography Markup Language) — Del 2: Udvidede skemaer 
og kodningsregler_.

[NOTE] 
====
Skemaerne for GML 3.3 ligger på
http://schemas.opengis.net/gml/3.3/[http://schemas.opengis.net/gml/3.3/,title=skemaerne for GML 3.3].

Standarden er moden, der forventes ikke nye versioner udover eventuelle
fejlrettelser.
==== 

[#gml-sf]
==== Geography Markup Language (GML) simple features profile

[.bibliographicaldetails] 
OGC 10-100r3, _Geography Markup Language (GML) simple features profile
(with Corrigendum)_. Version 2.0. 5 april 2012. Tilgængelig på:
http://portal.opengeospatial.org/files/?artifact_id=42729[http://portal.opengeospatial.org/files/?artifact_id=42729,title=Geography Markup Language (GML) simple features profile (with Corrigendum)] 

GML-standarden er en meget omfattende standard, og derfor har OGC
defineret et begrænset men nyttigt delmængde af den, for at få mere
software til at understøtte GML. Geography Markup Language simple
features profile (GML-SF) begrænser udvalget af geometrier i GML til 0-,
1-, og 2-dimensionelle geometrier beskrevet i 1-, 2-, eller
3-dimensionale koordinatreferencesystemer og begrænser antallet af måder
man kan indkode disse geometrier på.

GML-SF definerer tre compliance-niveauer, SF-0, SF-1 og SF-2. Niveau
SF-2 tillader en database der implementerer <<sfa-sql>> at
repræsentere de data, den måtte indeholde.

I modsætning til <<sfa-ca>> tillader GML-SF også bestemte indkodninger for
cirkelbuer og cirkler (`+gml:Arc+`, `+gml:Circle+` og `+gml:CircleByCenterPoint+`).

[#gpkg]
==== GeoPackage Encoding Standard 

[.bibliographicaldetails] 
OGC 12-128r15, _OGC® GeoPackage Encoding Standard - with Corrigendum_.
Version 1.2.1. 6 september 2018. Tilgængelig på:
http://www.geopackage.org/spec121/[http://www.geopackage.org/spec121/,title=OGC® GeoPackage Encoding Standard - with Corrigendum] 

GeoPackage er baseret på SQLite, et relationelt
databasehåndteringssystem. Én GeoPackage-fil kan håndtere vektordata,
rasterdata, og metadata. Da en GeoPackage er en databasecontainer,
understøtter den direkte brug, fx til analyseformål.

GeoPackage er i overensstemmelse med <<sfa-ca>> og <<sfa-sql>>.

[NOTE] 
====
Arbejdsgruppen om GeoPackage er aktiv og der er mange ønsker til
videreudvikling af den. Derfor kan der forventes at komme flere
versioner.

Læs mere om GeoPackage på OGC’s blog:
https://www.ogc.org/blog/3148[#GeoPackageDay 2020 - what is GeoPackage?]

I Nederlandene er GeoPackage-standarden optaget på
https://www.forumstandaardisatie.nl/open-standaarden/verplicht[følg-eller-forklar
listen] af “Dutch Standardisation Forum”. Anvendelsesområdet for
GeoPackage er ifølge motiveringen for optagelse af listen følgende:
“GeoPackage skal anvendes når det offentlige tilbyder geodata til
download til tredjepart”.

Dutch Standardisation Forum understreger også, at “GeoPackage ikke ses
som en erstatning, men som et supplement til brugen af GML”.

GeoPackage ses at være en erstatning for shapefiler.

Der eksisterer ikke endnu et komplet sæt regler, der definerer, hvordan
man på systematisk vis kan omsætte en logisk datamodel der er i
overensstemmelse med <<19103,DS/ISO 19103>> til en GeoPackage template.

GeoPackage anvendes typisk til udveksling af hele datasæt (fildownload).

GeoPackage bør bruges når man vil distribuere data i andre formater, ved
siden af GML.
==== 

[#pdf-georegistration]
==== PDF Georegistration Encoding Best Practice 

[.bibliographicaldetails] 
OGC 08-139r3, _PDF Georegistration Encoding Best Practice_. OGC Best
Practice. Version 2.2. 17 januar 2011. Tilgængelig på:
https://portal.opengeospatial.org/files/?artifact_id=40537[https://portal.opengeospatial.org/files/?artifact_id=40537,title=PDF Georegistration Encoding Best Practice] 

Denne OGC best practice beskriver hvordan man kan lave PDF-dokumenter
der er georefererede.

[NOTE] 
====
Se følgende dokumenter for mere information angående georefererede
PDF-dokumenter:

* A PDF Tile Model for Geographic Map Data <<zamx19>>
* Creating Maps for the Non-Mapper <<capu10>>
====

JSON og GeoJSON, anvendes typisk til udveksling af et udvalg af features
fra et datasæt via en webtjeneste, er ikke med i ovenstående oversigt.
Det skyldes, at måden, hvorpå geodata kan indkodes i JSON ikke er
standardiseret endnu.

JSON <<rfc-8259>>, GeoJSON <<rfc-7946>> og https://json-schema.org/[JSON Schema] 
<<json-schema>> er udviklet
i regi af Internet Engineering Task Force (IETF):

Bemærk, at <<rfc-7946>> og <<rfc-8259>> ikke er officielle IETF-standarder
endnu.

OGC er i gang med at udarbejde en
https://github.com/opengeospatial/architecture-dwg/tree/master/json-best-practice[JSON
Best Practice], en OGC Best Practice for hvordan man kan anvende JSON
som indkodning for OGC-standarden. Indholdet er især baseret på 
_Testbed-12 JSON and GeoJSON User Guide_ <<ogc-16-122r1>> og
_Testbed-12 Javascript-JSON-JSON-LD Engineering Report_ <<ogc-16-051>>, 
og er inspireret af en del andre OGC-dokumenter om JSON.
