[#tjenester]
=== Udveksling af geodata - tjenester 

De tre vigtigste typer tjenester for geodata er søgetjenester (så man
kan søge og finde data, vha. metadata), downloadtjenester (så man kan
hente data) og visningstjenester (så man kan se data visualiseret).

OGC har defineret en suite af standarder som definerer snitfladerne
mellem klienter og disse tjenester, hvoraf de vigtigste og mest kendte
er <<wms,Web Map Service (WMS)>>, <<wmts,Web Map Tile Service (WMTS)>> 
og <<wfs,Web Feature Service (WFS)>>. Derudover findes der fx
https://www.ogc.org/standards/wcs[Web Coverage Service (WCS)] og
https://www.ogc.org/standards/sos[Sensor Observation Service
(SOS)], som ikke er beskrevet yderligere her.

OGC er ved at definere en ny, moderniseret, suite af standarder, som
understøtter de samme brugsscenarier, og som anvender de nuværende best
practices for at dele data på webbet, se også
https://ogcapi.ogc.org/.

[#wfs] 
==== Web Feature Service (WFS) 

[.bibliographicaldetails]
OGC 09-025r2, _OGC® Web Feature Service 2.0 Interface Standard – With
Corrigendum_. Version 2.0.2. 10 juli 2014. Tilgængelig på:
http://docs.opengeospatial.org/is/09-025r2/09-025r2.html[http://docs.opengeospatial.org/is/09-025r2/09-025r2.html,title=OGC® Web Feature Service 2.0 Interface Standard – With Corrigendum]

Denne OGC-standard beskriver snitfladen mellem en klient og en
downloadtjeneste, Web Feature Service (WFS), som udstiller vektordata på
objekt- og attributniveau.

En WFS-tjeneste skal understøtte kommunikation vha. HTTP og svarer i
XML.

Standarden definerer forskellige typer af WFS-tjenester. For alle typer
gælder, at de skal kunne returnere vektordata i GML.

Version 2.0.0 af denne OGC-standard er også kendt som DS/EN ISO
19142:2011, _Geografisk information — Web Feature Service_.

[NOTE]
====
Modsætningen af distribution af vektordata på objekt- og attributniveau
er distribution af vektordata på datasætniveau, såsom fildownload via
File Transfer Protocol (FTP)).

Det kan lade sig gøre, at bruge WFS til at understøtte download af et
helt datasæt på en gang (i én forespørgsel), men det frarådes for store
datasæt.
==== 

[#tg-download] 
==== INSPIRE Download Services

[.bibliographicaldetails]
_Technical Guidance for the implementation of INSPIRE Download
Services_. Version 3.1. 9 august 2013. Tilgængelig på:
https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-download-services[https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-download-services,title=Technical Guidance for the implementation of INSPIRE Download Services] 

Denne INSPIRE-vejledning beskriver hvordan man kan leve op til INSPIREs
krav om downloadtjenester ved hjælp af bl.a. <<wfs,WFS 2.0>>.

[NOTE]
====
Se også ovenstående forbehold hvad angår store datasæt.

Man kan teste om en tjeneste er i overensstemmelse med vejledningen vha.
http://inspire.ec.europa.eu/validator/[INSPIRE's validator].
====

[#wms] 
==== Web Map Server (WMS)

[.bibliographicaldetails]
OGC 06-042, _OpenGIS® Web Map Server Implementation Specification_.
Version 1.3.0. 15 marts 2006. Tilgængelig på:
http://portal.opengeospatial.org/files/?artifact_id=14416[http://portal.opengeospatial.org/files/?artifact_id=14416,title=OpenGIS® Web Map Server Implementation Specification]

Denne OGC-standard beskriver snitfladen mellem en klient og en
visningstjeneste, Web Map Service (WMS), som udstiller dynamisk
genererede georefererede billeder (fx i PNG-formatet).

Denne standard er også kendt som DS/EN ISO 19128:2008, _Geografisk
information — Web Map Server-grænseflade_.

[#sld]
==== Styled Layer Descriptor (SLD)

[.bibliographicaldetails]
OGC 05-078r4, _Styled Layer Descriptor profile of the Web Map Service
Implementation Specification_. Version 1.1.0. 29 juni 2007. Tilgængelig
på:
http://portal.opengeospatial.org/files/?artifact_id=22364[http://portal.opengeospatial.org/files/?artifact_id=22364,title=Styled Layer Descriptor profile of the Web Map Service Implementation Specification] 

Denne OGC-standard, Styled Layer Descriptor (SLD), beskriver hvordan en
WMS kan udvides så den tillader brugerdefineret styling vha. <<se>>.

[NOTE]
Sammen med <<se>> er denne
standard efterfølgeren til SLD 1.0.

[#se] 
==== Symbology Encoding Implementation Specification

[.bibliographicaldetails]
OGC 05-077r4, _Symbology Encoding Implementation Specification_. Version
1.1.0. 21 juli 2006. Tilgængelig på:
http://portal.opengeospatial.org/files/?artifact_id=16700[http://portal.opengeospatial.org/files/?artifact_id=16700,title=Symbology Encoding Implementation Specification]

Denne OGC-standard definerer et sprog for præsentation af geodata (styling).

[#wmts] 
==== Web Map Tile Service (WMTS)

[.bibliographicaldetails]
OGC 07-057r7, _OpenGIS® Web Map Tile Service Implementation Standard_.
Version 1.0.0. 6 april 2010. Tilgængelig på:
http://portal.opengeospatial.org/files/?artifact_id=35326[http://portal.opengeospatial.org/files/?artifact_id=35326,title=OpenGIS® Web Map Tile Service Implementation Standard] 

Denne OGC-standard beskriver snitfladen mellem en klient og en
visningstjeneste, Web Map Tile Service (WMTS), som udstiller
forhåndsgenererede georefererede billeder (fx i PNG-formatet).

[NOTE]
Fordi billederne er genereret på forhånd, er performance af WMTS-tjenester bedre end af <<wms,WMS-tjenester>>. 

[#tg-view] 
==== INSPIRE View Services

[.bibliographicaldetails]
_Technical Guidance for the implementation of INSPIRE View Services_. Version 3.11. 4 april 2013. Tilgængelig på: https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-view-services-1[https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-view-services-1,title=Technical Guidance for the implementation of INSPIRE View Services] 

Denne INSPIRE-vejledning beskriver, hvordan man kan leve op til INSPIREs
krav om visningstjenester ved hjælp af <<wms,WMS 1.3.0>> (den anbefalede måde
fra INSPIREs side), <<wmts,WMTS 1.0.0>> og WMS 1.1.1 <<ogc-01-068r3>>.

[NOTE] 
Man kan teste om en tjeneste er i overensstemmelse med vejledningen vha.
http://inspire.ec.europa.eu/validator/[INSPIRE's validator].

[#csw]
==== Catalogue Services (CSW) 

[.bibliographicaldetails]
OGC 07-006r1, _OpenGIS® Catalogue Services Specification_. Version
2.0.2. 23 februar 2007. Tilgængelig på:
http://portal.opengeospatial.org/files/?artifact_id=20555[http://portal.opengeospatial.org/files/?artifact_id=20555,title=OpenGIS® Catalogue Services Specification] 

Denne OGC-standard definerer snitfladen mellem en klient og en
søgetjeneste, Catalogue Service for the Web (CSW), som udstiller
metadata og har operationer så man kan søge på de forskellige felter.

[NOTE]
https://geodata-info.dk/srv/eng/csw?request=GetCapabilities&service=CSW&version=2.0.2[Geodata-info]
er i overensstemmelse med denne standard.

[#csw-iso-ap]
==== CSW - ISO Metadata Application Profile

[.bibliographicaldetails]
OGC 07-045r1, _OpenGIS® Catalogue Services Specification 2.0.2 - ISO
Metadata Application Profile: Corrigendum_. 9 marts 2018. Tilgængelig
på:
https://portal.opengeospatial.org/files/?artifact_id=77855[https://portal.opengeospatial.org/files/?artifact_id=77855,title=OpenGIS® Catalogue Services Specification 2.0.2 - ISO Metadata Application Profile: Corrigendum] 

Denne OGC-standard definerer hvordan man anvender <<csw>> sammen
med metadata som specificeret i <<19115,DS/EN ISO 19115>>.

[NOTE]
https://geodata-info.dk/srv/eng/csw?request=GetCapabilities&service=CSW&version=2.0.2[Geodata-info]
er i overensstemmelse med denne standard.

[#ogcfeat] 
==== OGC API - Features - Part 1: Core

[.bibliographicaldetails]
_OGC API - Features - Part 1: Core_. Version 1.0. 7 oktober 2019.
Tilgængelig på:
http://docs.opengeospatial.org/is/17-069r3/17-069r3.html[http://docs.opengeospatial.org/is/17-069r3/17-069r3.html,title=OGC API - Features - Part 1: Core]

Denne OGC-standard er den første af OGCs nye suite af API-standarder.

[NOTE]
I INSPIRE-regi er man i skrivende stund i gang med at kigge på, hvordan
man kan leve op til INSPIREs krav om downloadtjenester ved hjælp af
denne standard.
